version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: uaosuperdev707
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - CONNECTION_STRING=mongodb://root:uaosuperdev707@mongodb:27017/
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    command: npm run dev -- --host 0.0.0.0

volumes:
  mongo-data:
