version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: uaosuperdev707
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://root:uaosuperdev707@mongodb:27017
    command: node dist/main.js

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    command: npm run dev

volumes:
  mongo-data:
